// Shopify storefront config — the Printful-fulfilled "Lake Lure Insider Shop".
// See claude project doc "merch-store-pod-vendor-decision" for the full setup story.

export const SHOPIFY_DOMAIN = 'dvui01-qr.myshopify.com'

// Storefront API access token for the Buy Button sales channel — public/
// embeddable (scoped to storefront reads + checkout creation only, not the
// Admin API), generated by Pete via Shopify Admin -> Settings -> Apps and
// sales channels -> Buy Button -> create a Buy Button -> "Get embed code".
export const SHOPIFY_STOREFRONT_ACCESS_TOKEN = '91bdc51175cdf01233580cc14802dd8e'

export interface ShopProductImage {
  src: string
  alt: string
}

export interface ShopProduct {
  /** Shopify numeric product ID, e.g. "10253124960576" */
  id: string
  handle: string
  title: string
  category: '100-dam-years' | 'tees' | 'hats' | 'hoodie-tank' | 'stickers' | 'magnets' | 'pins'
  /** One or two sentences of sales copy — shown on the /shop product card. */
  blurb: string
  /** Display-ready price string, e.g. "$18.50" or "From $22.50". */
  priceFrom: string
  /**
   * Highest variant price in USD, e.g. 33 or 37.09. Feeds the schema.org
   * AggregateOffer on /shop (the low end is parsed from `priceFrom`). Update
   * both whenever prices change in Shopify.
   */
  priceHigh: number
  /** Short spec shown next to the price, e.g. "12 colors" or "3 sizes". */
  variantNote: string
  image: ShopProductImage
  backImage?: ShopProductImage
}

export const SHOP_PRODUCTS = {
  'edmund-for-mayor-tee': {
    id: '10253124960576',
    handle: 'unisex-classic-tee-1',
    title: 'Edmund for Mayor Tee',
    category: 'tees',
    blurb:
      'Edmund in a red bow tie and star-spangled rosette, waving to his constituents under a burst of stars and stripes, banked by "EDMUND FOR MAYOR" and "THE G.O.A.T. CANDIDATE." The back reads "A goat we can all get behind."',
    priceFrom: 'From $22.50',
    priceHigh: 33,
    variantNote: '12 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-classic-tee-sapphire-front-6a99606bcb89c.jpg?v=1788436599',
      alt: 'Front of the Edmund for Mayor Tee in sapphire blue, showing the vintage campaign badge design',
    },
    backImage: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-classic-tee-sapphire-back-6a99606bcbaaf.jpg?v=1788436599',
      alt: "Back of the Edmund for Mayor Tee in sapphire blue, printed with the phrase 'A goat we can all get behind'",
    },
  },
  'edmund-for-mayor-badge-tee': {
    id: '10253146358080',
    handle: 'edmund-for-mayor',
    title: 'Edmund for Mayor Vintage Badge Tee',
    category: 'tees',
    blurb:
      'A quieter, single-print take: a hand-illustrated portrait of Edmund set against layered mountains and pines, ringed by a distressed gold arc, with "EDMUND FOR MAYOR" and "LAKE LURE, NC" lettered below. Front print only.',
    priceFrom: 'From $23.50',
    priceHigh: 35,
    variantNote: '12 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-classic-tee-sapphire-front-6a996552d0389.jpg?v=1788437866',
      alt: 'Front of the Edmund for Mayor Vintage Badge Tee in sapphire blue, showing the hand-illustrated vintage badge design',
    },
  },
  'lake-life-goat-life-tee': {
    id: '10253828784448',
    handle: 'unisex-garment-dyed-heavyweight-t-shirt',
    title: 'Edmund Lake Life. Goat Life. Heavyweight Tee',
    category: 'tees',
    blurb:
      'Edmund floating chest-deep in the lake, sunglasses on, Chimney Rock behind him, ringed by "EDMUND" and "LAKE LIFE. GOAT LIFE." The back is his mission statement: "I cross rivers. I ignore fences. I do what I want."',
    priceFrom: 'From $28.50',
    priceHigh: 36,
    variantNote: '11 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-garment-dyed-heavyweight-t-shirt-berry-front-6a9ac69a7195e.jpg?v=1788528327',
      alt: 'Front of the Edmund Lake Life. Goat Life. Heavyweight Tee in berry, showing Edmund floating in the lake wearing sunglasses',
    },
    backImage: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-garment-dyed-heavyweight-t-shirt-berry-back-6a9ac69a72b14.jpg?v=1788528327',
      alt: "Back of the Edmund Lake Life. Goat Life. Heavyweight Tee in berry, printed with 'I cross rivers. I ignore fences. I do what I want.'",
    },
  },
  'heritage-mountain-hat': {
    id: '10253182075200',
    handle: 'heritage-mountain-edmund-logo',
    title: 'Edmund Mountain Badge Dad Hat',
    category: 'hats',
    blurb:
      'A national-park-style badge: Edmund standing watch over the Blue Ridge, ringed by pine trees and layered peaks, with "EDMUND" and "LAKE LURE, NC" stitched below.',
    priceFrom: '$19.50',
    priceHigh: 19.5,
    variantNote: '3 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/distressed-dad-hat-black-front-6a996a18a5958.jpg?v=1788439090',
      alt: 'Edmund Mountain Badge Dad Hat in black, showing the embroidered mountain badge patch',
    },
  },
  'edmund-sunglasses-hat': {
    id: '10253194035520',
    handle: 'edmund-hat-sunglasses',
    title: 'Edmund in Shades Dad Hat',
    category: 'hats',
    blurb:
      "Edmund's celebrity portrait, sunglasses and all, embroidered on a circular badge with \"EDMUND\" arched over the top and \"LAKE LURE, NC\" lettered below between two stars.",
    priceFrom: '$18.50',
    priceHigh: 18.5,
    variantNote: '10 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/classic-dad-hat-navy-front-6a996b6db0555.jpg?v=1788439447',
      alt: 'Edmund in Shades Dad Hat in navy, showing the embroidered sunglasses portrait badge',
    },
  },
  'dont-fence-me-in-hat': {
    id: '10253199475008',
    handle: 'dont-fence-me-in-edmund',
    title: "Don't Fence Me In Dad Hat",
    category: 'hats',
    blurb:
      "The catchphrase from Andrea Martin's viral Edmund reel, embroidered on an oval badge: Edmund strolling past a broken wooden fence with the lake and mountains behind him.",
    priceFrom: '$18.50',
    priceHigh: 18.5,
    variantNote: '8 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/classic-dad-hat-navy-front-6a996c44e8cd7.jpg?v=1788439652',
      alt: "Don't Fence Me In Dad Hat in navy, showing the embroidered oval badge of Edmund by a broken fence",
    },
  },
  'chimney-rock-escape-hoodie': {
    id: '10253222281536',
    handle: 'unisex-hoodie-chimney-rock-escape-artist',
    title: 'Edmund Chimney Rock Escape Artist Hoodie',
    category: 'hoodie-tank',
    blurb:
      'Edmund perched above the tree line with a flag planted on the rock behind him, silhouetted against a Blue Ridge sunset, "EDMUND" lettered bold above "CHIMNEY ROCK ESCAPE ARTIST." The back sums up months of #FreeEdmund updates: "If they chase me, I run faster."',
    priceFrom: 'From $44',
    priceHigh: 49.5,
    variantNote: '13 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-premium-pullover-hoodie-white-front-6a997f2571624.jpg?v=1788444471',
      alt: 'Front of the Edmund Chimney Rock Escape Artist Hoodie in white, showing Edmund silhouetted atop the rock at sunset',
    },
    backImage: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-premium-pullover-hoodie-white-back-6a997f2574b59.jpg?v=1788444471',
      alt: "Back of the Edmund Chimney Rock Escape Artist Hoodie in white, printed with 'If they chase me, I run faster.'",
    },
  },
  'lake-float-tank': {
    id: '10253268812096',
    handle: 'unisex-tank-top',
    title: 'Edmund Lake Float Tank Top',
    category: 'hoodie-tank',
    blurb:
      "Sunglasses on, floating in an inner tube with the mountains behind him — Edmund doing exactly what everyone else does at Lake Lure in July. The back is a pun made for the dock: \"Goats just wanna have sun.\"",
    priceFrom: 'From $27',
    priceHigh: 29.5,
    variantNote: '3 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-staple-tank-top-red-front-6a99a1713ac9d.jpg?v=1788453259',
      alt: 'Front of the Edmund Lake Float Tank Top in red, showing Edmund floating in an inner tube on the lake',
    },
    backImage: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-staple-tank-top-red-back-6a99a1713b843.jpg?v=1788453259',
      alt: "Back of the Edmund Lake Float Tank Top in red, printed with 'Goats just wanna have sun.'",
    },
  },
  'edmund-sunglasses-sticker': {
    id: '10253830684992',
    handle: 'bubble-free-stickers',
    title: 'Edmund in Shades Sticker',
    category: 'stickers',
    blurb:
      'The same circular portrait from the Edmund in Shades Dad Hat, printed as a durable vinyl sticker. Laptop, water bottle, bumper — your call.',
    priceFrom: 'From $3',
    priceHigh: 3.5,
    variantNote: '3 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/kiss-cut-stickers-white-3x3-default-6a9ac79a56912.jpg?v=1788528543',
      alt: 'Edmund in Shades sticker, showing the sunglasses portrait badge',
    },
  },
  'heritage-mountain-sticker': {
    id: '10253831864640',
    handle: 'bubble-free-stickers-1',
    title: 'Edmund Mountain Badge Sticker',
    category: 'stickers',
    blurb: 'The national-park-style badge from the Mountain Badge Dad Hat, sized down to a sticker.',
    priceFrom: 'From $3',
    priceHigh: 3.5,
    variantNote: '3 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/kiss-cut-stickers-white-3x3-default-6a9ac80b74400.jpg?v=1788528656',
      alt: "Edmund Mountain Badge sticker, showing Edmund's silhouette on a mountain badge",
    },
  },
  'dont-fence-me-in-sticker': {
    id: '10253834944832',
    handle: 'dont-fence-me-in-edmund-sticker',
    title: "Don't Fence Me In Sticker",
    category: 'stickers',
    blurb:
      "Edmund strolling past a broken wooden fence, framed in an oval badge — the same design from the Don't Fence Me In Dad Hat, now in sticker form.",
    priceFrom: 'From $3',
    priceHigh: 3.5,
    variantNote: '3 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/kiss-cut-stickers-white-3x3-default-6a9ac87062152.jpg?v=1788528756',
      alt: "Don't Fence Me In sticker, showing Edmund walking past a broken fence",
    },
  },
  'edmund-for-mayor-sticker': {
    id: '10273618166080',
    handle: 'edmund-for-mayor-sticker',
    title: 'Edmund for Mayor Sticker',
    category: 'stickers',
    blurb:
      "Edmund's vintage-style campaign badge — bow tie, ribbon, and all — printed as a durable vinyl sticker. Laptop, water bottle, bumper — your call.",
    priceFrom: 'From $3.50',
    priceHigh: 4,
    variantNote: '3 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/kiss-cut-stickers-white-3x3-default-6aada4eace3e4.jpg?v=1789764850',
      alt: 'Edmund for Mayor sticker, showing the vintage campaign badge design',
    },
  },
  'holographic-edmund-for-mayor-sticker': {
    id: '10273654669632',
    handle: 'holographic-edmund-for-mayor-sticker',
    title: 'Holographic Edmund for Mayor Sticker',
    category: 'stickers',
    blurb:
      'The same Edmund for Mayor campaign badge, printed on holographic vinyl that shifts color as the light hits it. Same goat, same platform, more sparkle. Indoor use only.',
    priceFrom: 'From $5.50',
    priceHigh: 6,
    variantNote: '2 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/kiss-cut-holographic-stickers-grey-3x3-front-6aada69260424.jpg?v=1789765273',
      alt: 'Holographic Edmund for Mayor sticker, showing the campaign badge design with a rainbow shimmer finish',
    },
  },
  'edmund-lake-life-goat-life-sticker': {
    id: '10273680884032',
    handle: 'edmund-lake-life-goat-life-sticker',
    title: 'Edmund Lake Life. Goat Life. Sticker',
    category: 'stickers',
    blurb:
      'Edmund chest-deep in the lake with Chimney Rock behind him — the same crest from the heavyweight tee, printed as a durable vinyl sticker.',
    priceFrom: 'From $3.50',
    priceHigh: 4,
    variantNote: '3 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/kiss-cut-stickers-white-3x3-default-6aada76e8754e.jpg?v=1789765499',
      alt: 'Edmund Lake Life. Goat Life. sticker, showing Edmund swimming in the lake with Chimney Rock behind him',
    },
  },
  'edmund-for-mayor-magnet': {
    id: '10273643659584',
    handle: 'edmund-for-mayor-magnet',
    title: 'Edmund for Mayor Magnet',
    category: 'magnets',
    blurb:
      "Edmund's campaign badge printed as a durable vinyl magnet. Fridge, filing cabinet, toolbox — wherever you keep the things that matter.",
    priceFrom: 'From $4.50',
    priceHigh: 7,
    variantNote: '3 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/die-cut-magnets-white-3x3-front-6aada643e0ed5.jpg?v=1789765194',
      alt: 'Edmund for Mayor magnet, showing the vintage campaign badge design',
    },
  },
  'edmund-goat-pin-button-set': {
    id: '10273691238720',
    handle: 'set-of-edmund-the-goat-pin-buttons',
    title: 'Set of Edmund the Goat Pin Buttons',
    category: 'pins',
    blurb:
      "Five pins pulling from Edmund's whole lineup — the campaign badge, the mountain patch, the Lake Life crest, and the goat on his lake float. Pin them on a jacket, backpack, or hat band.",
    priceFrom: 'From $10',
    priceHigh: 11.5,
    variantNote: '2 sizes',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/set-of-pin-buttons-white-1.25-front-2-6aada84d7ee1e.jpg?v=1789765737',
      alt: 'Set of 5 Edmund the Goat pin buttons, showing the campaign badge, mountain patch, lake life, and lake float designs',
    },
  },
  'goat-float-tee': {
    id: '10277032591680',
    handle: '100-dam-years-edmund-goat-float',
    title: '100 Dam Years Edmund Goat Float Tee',
    category: '100-dam-years',
    blurb:
      'Edmund reclines on a yellow inner tube in mirrored shades, "LAKE LURE" tumbler in hoof, while the dam spills behind him under "100 DAM YEARS." The sign below reads "LAKE LURE, NC · 1926 – 2026."',
    priceFrom: 'From $15.50',
    priceHigh: 26,
    variantNote: '11 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-staple-t-shirt-heather-true-royal-front-6ab08dc021036.jpg?v=1789955544',
      alt: 'Front of the 100 Dam Years Edmund Goat Float Tee in heather true royal, showing a goat in sunglasses floating on a yellow inner tube in front of the Lake Lure Dam',
    },
  },
  'goat-float-womens-tee': {
    id: '10277033574720',
    handle: '100-dam-years-edmund-goat-float-womens-relaxed-t-shirt',
    title: "100 Dam Years Edmund Goat Float Women's Relaxed Tee",
    category: '100-dam-years',
    blurb:
      'The goat float in a relaxed women\'s cut: Edmund on his inner tube, the Lake Lure Dam behind him, "100 DAM YEARS" overhead. Soft, smooth, and easy to dress up or down.',
    priceFrom: 'From $18.50',
    priceHigh: 23.5,
    variantNote: '10 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/womens-relaxed-t-shirt-heather-true-royal-front-6ab08ea5790a6.jpg?v=1789955761',
      alt: "Front of the 100 Dam Years Edmund Goat Float Women's Relaxed Tee in heather true royal, showing a goat in sunglasses floating on an inner tube in front of the Lake Lure Dam",
    },
  },
  'goat-float-mens-long-sleeve': {
    id: '10277033836864',
    handle: '100-dam-years-edmund-goat-float-men-s-long-sleeve-shirt',
    title: "Men's 100 Dam Years Edmund Goat Float Long Sleeve Tee",
    category: '100-dam-years',
    blurb:
      'Same goat, same inner tube, now with sleeves. A classic-fit long sleeve with ribbed cuffs, made for cool mornings on the pier.',
    priceFrom: 'From $20',
    priceHigh: 27.5,
    variantNote: '10 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-long-sleeve-shirt-indigo-blue-front-6ab08f2a5a823.jpg?v=1789955891',
      alt: "Front of the Men's 100 Dam Years Edmund Goat Float Long Sleeve Tee in indigo blue, showing a goat in sunglasses floating on an inner tube in front of the Lake Lure Dam",
    },
  },
  'dam-blueprint-tee': {
    id: '10274452046144',
    handle: 'blueprint-classic-tee',
    title: 'Lake Lure Dam Blueprint Tee: Structure No. 1926',
    category: '100-dam-years',
    blurb:
      'Structure No. 1926, now in cotton. Engineering-drawing linework of the Lake Lure Dam with gold dimension lines, printed light on six dark colors. Front print only.',
    priceFrom: 'From $13.50',
    priceHigh: 23,
    variantNote: '6 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-classic-tee-navy-front-6aaf5e86690e6.jpg?v=1789877915',
      alt: 'Front of the Lake Lure Dam Blueprint Tee in navy, showing white and gold engineering-drawing linework of the dam with a Structure No. 1926 title block',
    },
  },
  'centennial-crewneck-sweatshirt': {
    id: '10274449916224',
    handle: 'unisex-premium-sweatshirt',
    title: '100 Dam Years Centennial Crewneck Sweatshirt',
    category: '100-dam-years',
    blurb:
      'The centennial badge (sunrise over the Blue Ridge, "100 DAM YEARS," "LAKE LURE, NC · 1926 – 2026") on a soft fleece crewneck. Its cream background pops on all 12 colors.',
    priceFrom: 'From $31.89',
    priceHigh: 37.09,
    variantNote: '12 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-premium-sweatshirt-navy-blazer-front-6aaf58647715b.jpg?v=1789876352',
      alt: 'Front of the 100 Dam Years Centennial Crewneck Sweatshirt in navy blazer, showing the hexagonal 100 Dam Years badge with a sunrise over the mountains',
    },
  },
  'centennial-heavyweight-long-sleeve': {
    id: '10274449785152',
    handle: 'mens-heavyweight-long-sleeve-t-shirt',
    title: "Men's 100 Dam Years Heavyweight Long Sleeve Tee",
    category: '100-dam-years',
    blurb:
      'The same centennial badge on a thick, soft-washed long sleeve. Five colors, built for cool lake mornings.',
    priceFrom: 'From $21.15',
    priceHigh: 26.35,
    variantNote: '5 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/mens-heavyweight-long-sleeve-t-shirt-black-front-6aaf58643e624.jpg?v=1789876338',
      alt: "Front of the Men's 100 Dam Years Heavyweight Long Sleeve Tee in black, showing the hexagonal 100 Dam Years badge with a sunrise over the mountains",
    },
  },
  'edmund-for-mayor-long-sleeve': {
    id: '10274447130944',
    handle: 'edmund-for-mayor-long-sleeve-tee',
    title: 'Edmund for Mayor Long Sleeve Tee',
    category: 'tees',
    blurb:
      'The original Edmund for Mayor campaign badge on a lightweight, ultra-soft long sleeve. The back still reads "A goat we can all get behind."',
    priceFrom: 'From $32',
    priceHigh: 35,
    variantNote: '10 colors',
    image: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-long-sleeve-tee-storm-front-6aaf548d085d8.jpg?v=1789875372',
      alt: 'Front of the Edmund for Mayor Long Sleeve Tee in storm gray, showing the vintage campaign badge design',
    },
    backImage: {
      src: 'https://cdn.shopify.com/s/files/1/0999/2228/0768/files/unisex-long-sleeve-tee-storm-back-6aaf548d0c5bb.jpg?v=1789875372',
      alt: "Back of the Edmund for Mayor Long Sleeve Tee in storm gray, printed with the phrase 'A goat we can all get behind'",
    },
  },
} as const satisfies Record<string, ShopProduct>

export type ShopProductKey = keyof typeof SHOP_PRODUCTS

export interface ShopCategory {
  slug: string
  label: string
  productKeys: ShopProductKey[]
}

// Display order for the /shop grid — grouped by category, each with an
// anchor slug the category nav pills jump to.
export const SHOP_CATEGORIES: ShopCategory[] = [
  {
    slug: '100-dam-years',
    label: '100 Dam Years',
    productKeys: [
      'goat-float-tee',
      'goat-float-womens-tee',
      'goat-float-mens-long-sleeve',
      'dam-blueprint-tee',
      'centennial-crewneck-sweatshirt',
      'centennial-heavyweight-long-sleeve',
    ],
  },
  {
    slug: 'tees',
    label: 'Tees & Long Sleeves',
    productKeys: [
      'edmund-for-mayor-tee',
      'edmund-for-mayor-badge-tee',
      'lake-life-goat-life-tee',
      'edmund-for-mayor-long-sleeve',
    ],
  },
  {
    slug: 'hats',
    label: 'Hats',
    productKeys: ['heritage-mountain-hat', 'edmund-sunglasses-hat', 'dont-fence-me-in-hat'],
  },
  {
    slug: 'hoodie-tank',
    label: 'Hoodie & Tank',
    productKeys: ['chimney-rock-escape-hoodie', 'lake-float-tank'],
  },
  {
    slug: 'stickers',
    label: 'Stickers',
    productKeys: [
      'edmund-sunglasses-sticker',
      'heritage-mountain-sticker',
      'dont-fence-me-in-sticker',
      'edmund-for-mayor-sticker',
      'holographic-edmund-for-mayor-sticker',
      'edmund-lake-life-goat-life-sticker',
    ],
  },
  {
    slug: 'magnets',
    label: 'Magnets',
    productKeys: ['edmund-for-mayor-magnet'],
  },
  {
    slug: 'pins',
    label: 'Pins',
    productKeys: ['edmund-goat-pin-button-set'],
  },
]
