// Shopify storefront config — the Printful-fulfilled "Lake Lure Insider Shop".
// See claude project doc "merch-store-pod-vendor-decision" for the full setup story.

export const SHOPIFY_DOMAIN = 'dvui01-qr.myshopify.com'

// Storefront API access token for the Buy Button sales channel — public/
// embeddable (scoped to storefront reads + checkout creation only, not the
// Admin API), generated by Pete via Shopify Admin -> Settings -> Apps and
// sales channels -> Buy Button -> create a Buy Button -> "Get embed code".
export const SHOPIFY_STOREFRONT_ACCESS_TOKEN = '91bdc51175cdf01233580cc14802dd8e'

export interface ShopProduct {
  /** Shopify numeric product ID, e.g. "10253124960576" */
  id: string
  handle: string
  title: string
}

export const SHOP_PRODUCTS: Record<string, ShopProduct> = {
  'edmund-for-mayor-tee': {
    id: '10253124960576',
    handle: 'unisex-classic-tee-1',
    title: 'Edmund for Mayor Tee',
  },
  'edmund-for-mayor-badge-tee': {
    id: '10253146358080',
    handle: 'edmund-for-mayor',
    title: 'Edmund for Mayor Vintage Badge Tee',
  },
  'heritage-mountain-hat': {
    id: '10253182075200',
    handle: 'heritage-mountain-edmund-logo',
    title: 'Heritage Mountain Edmund Logo Hat',
  },
  'edmund-sunglasses-hat': {
    id: '10253194035520',
    handle: 'edmund-hat-sunglasses',
    title: 'Edmund Hat Sunglasses',
  },
  'dont-fence-me-in-hat': {
    id: '10253199475008',
    handle: 'dont-fence-me-in-edmund',
    title: "Don't Fence Me In Edmund",
  },
}
